replicaCount: 2

image:
  repository: anvesh3231/task-manager-app
  tag: v1.0.0

service:
  type: LoadBalancer
  port: 80
  targetPort: 3000

namespace: task-manager

mongo:
  image: mongo:7
  storageSize: 1Gi

secretName: app-secrets